/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

/**
 *
 * @author domin
 */
public class Acerca_de extends javax.swing.JFrame {

    /**
     * Creates new form Acerca_de
     */
    public Acerca_de() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_fondo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_Logo = new javax.swing.JButton();
        btn_Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_fondo.setBackground(new java.awt.Color(102, 102, 102));
        panel_fondo.setForeground(new java.awt.Color(0, 0, 0));
        panel_fondo.setDoubleBuffered(false);
        panel_fondo.setFocusable(false);
        panel_fondo.setPreferredSize(new java.awt.Dimension(480, 500));
        panel_fondo.setRequestFocusEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("ACERCA DE:\n\nTASKMASTES ES UN ES GESTOR DE TAREAS CREADO CON EL FIN DE\nFACILITAR A NUESTROS CLIENTES LA ORGANIZACIÓN \nTRABAJOS DE SUS EMPRESAS Y/O PROYECTOS PERSONALES, \nPARA ASÍ PODER LLEVAR UN ORDEN DESDE LO MÁS \nPRIORITARIO HASTA UNA UNA SALIDA PARA EL DÍA DE \nMAÑANA.\n\nEL GESTOR DE TAREAS DE TASKMASTER TIENE LA FACILIDAD DE \nPODER GUARDAD TANTO EL NOMBRE DE LA TAREA, LA  FECHA Y \nHORA EXACTA DE CUANDO DEBE SER REALIZADA E INCLUSO TE \nPERMITIRÁ DAR UNA BREVE DESCRIPCIÓN SOBRE LA TAREA A \nREALIZAR. PODRAS CONSULTAR TUS TAREAS PENDIENTE, \nEDITARLAS, YA SE QUE DEBAS HACERLO PARA UN TIEMPO MÁS\nCERCANO O MÁS LEJANO, Y PODRÁS ELIMINA LAS TARAS UNA VEZ \nYA HECHAS.\n\nPROVEEDOR: RapidEnCode Technology\nCreadores: Rossy Soriano, Sebastian Escaño y Erlyn Valerio\n\n\nVERSION INICIAL DEL SISTEMA: TaskMaster v0.1");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextArea1.setFocusable(false);
        jTextArea1.setMinimumSize(new java.awt.Dimension(470, 477));
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        btn_Logo.setBackground(new java.awt.Color(102, 102, 102));
        btn_Logo.setForeground(new java.awt.Color(102, 102, 102));
        btn_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asistente-de-robot.png"))); // NOI18N
        btn_Logo.setBorder(null);
        btn_Logo.setBorderPainted(false);
        btn_Logo.setContentAreaFilled(false);
        btn_Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Logo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asistente-de-robot.png"))); // NOI18N
        btn_Logo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asistente-de-robot.png"))); // NOI18N
        btn_Logo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asistente-de-robot.png"))); // NOI18N
        btn_Logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoActionPerformed(evt);
            }
        });

        btn_Volver.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btn_Volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_Volver.setIcon(new javax.swing.ImageIcon("C:\\Users\\domin\\Desktop\\Java Driver\\flecha-hacia-atras.png")); // NOI18N
        btn_Volver.setText("Volver");
        btn_Volver.setToolTipText("");
        btn_Volver.setBorder(null);
        btn_Volver.setBorderPainted(false);
        btn_Volver.setContentAreaFilled(false);
        btn_Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addComponent(btn_Volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Logo)
                        .addGap(38, 38, 38))))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Volver)
                    .addComponent(btn_Logo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jScrollPane1.setViewportView(panel_fondo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LogoActionPerformed

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        Menu menu = new Menu(); // Crea una instancia del JFrame form Menú
    menu.setVisible(true); // Haz visible el JFrame form Menú
    this.dispose(); // 
    }//GEN-LAST:event_btn_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acerca_de.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acerca_de.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acerca_de.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acerca_de.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acerca_de().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Logo;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panel_fondo;
    // End of variables declaration//GEN-END:variables
}
